# Generated by Django 5.0.6 on 2025-07-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dareexchange',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
