# Generated by Django 5.0.6 on 2025-07-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_dareexchange_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='dareexchange',
            name='phone_number',
            field=models.CharField(default=8585858585, max_length=10),
            preserve_default=False,
        ),
    ]
