# Generated by Django 4.2.22 on 2025-07-21 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_student_options_alter_student_profile'),
        ('home', '0006_dareexchange_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dareexchange',
            name='email',
        ),
        migrations.RemoveField(
            model_name='dareexchange',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dareexchange',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='dareexchange',
            name='user',
        ),
        migrations.AddField(
            model_name='dareexchange',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dareexchange',
            name='title',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
